### ISSUE TITLE
Classification Results

### ISSUE THREAD

**Issue by msergenergen** [marco-rudolph/differnet#11]
How can i see classification result without localization? Such as, good and different. Is this possible?

**Comment by marco-rudolph** [comment]
The output is not the class membership (defect or non-defect), but a score that is an indicator for defects. For a classification, you would have to set a special threshold that is applied to the anomaly score (see Section 3.2 in [the paper](https://arxiv.org/pdf/2008.12577.pdf)). Since different false positive rates can be targeted, there is no _perfect_ threshold. Setting the threshold to maximise accuracy, for example, makes little sense here, as the class distribution of defects and non-defects is not realistic in practice.

**Comment by msergenergen** [comment]
Firstly, thanks for your answer. I read article completely. Article is very impressive. I will define threshold value for own dataset. Is scoring function available in this repo? Will it happen in the future?

**Comment by marco-rudolph** [comment]
Thank you!
[This line](https://github.com/marco-rudolph/differnet/blob/a484c6aebf8c82c48380770dfc34397182775e4a/train.py#L89) computes the anomaly score.
