### ISSUE TITLE
UserWarning

### ISSUE THREAD

**Issue by jeff-ai-deep-learning** [marco-rudolph/differnet#16]
When I run the program, get following issue
\functional.py:942: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(

**Comment by marco-rudolph** [comment]
This error is unknown to me. Did you use the dependencies from requirements.txt?
I suspect the error is thrown in [this line?](https://github.com/marco-rudolph/differnet/blob/13c79a49f73a81b095ca1da9ad0c8fdc5ef1d86a/model.py#L40) Since no interpolation mode is passed, it sounds like something is wrong within your framework.
