### ISSUE TITLE
test_loss is super large, is that normal？

### ISSUE THREAD

**Issue by renqiqi** [marco-rudolph/differnet#17]
when I trained the net on my own dataset, the test_loss is super large, I do not know is right or not. 
Can you give me some advice?

`
Compute loss and scores on test set:
Epoch:1     test_loss:30636857344.0000
AUROC:   last:0.9935   max:0.9935   epoch_max:1
`

**Comment by marco-rudolph** [comment]
As long as this is only because the anomalies in the test set have a high loss, which is good because then they are considered unlikely, it doesn't matter. These scores can distort the mean loss very much.
In your case it seems to work anyway, when I look at the AUROC value.
Perhaps it would be better to measure the loss separately for the anomalies and normal data. On the non-anomalies the loss should be low.

**Comment by renqiqi** [comment]
> As long as this is only because the anomalies in the test set have a high loss, which is good because then they are considered unlikely, it doesn't matter. These scores can distort the mean loss very much.
> In your case it seems to work anyway, when I look at the AUROC value.
> Perhaps it would be better to measure the loss separately for the anomalies and normal data. On the non-anomalies the loss should be low.

thanks for your reply.
