### ISSUE TITLE
test on the good sample of dummy_dataset

### ISSUE THREAD

**Issue by lihyin** [marco-rudolph/differnet#2]
![Capture](https://user-images.githubusercontent.com/1203665/93051281-75448580-f621-11ea-9354-cd28b950e838.PNG)

Tried to test the false alarm by using the good sample. It lable the square as anomaly as well. Is it normal as expected?

**Comment by marco-rudolph** [comment]
The colormap is normed for every single sample so that the maximum gradient value for every sample appears yellow. See 'save_imgs' in localization.py:
`normed_grad = (grad[g] - np.min(grad[g])) / (np.max(grad[g]) - np.min(grad[g]))`
A common normalization of the gradients should lead to different intensities for anomalies and good samples. Then a common setting of vmin and vmax in plt.imshow should do the trick.
