### ISSUE TITLE
Can this work process one channel pics?

### ISSUE THREAD

**Issue by ghost** [marco-rudolph/differnet#36]
Hi,
Thank you very much for your work.
Can it be possible for this code to process only one channel of images?

**Comment by marco-rudolph** [comment]
Hi,
since the feature extractor is pretrained on the RGB dataset ImageNet, you will have to convert your image into RGB. For converted grayscale images helpful features should still be found from my experience. Otherwise you would have to use a feature extractor that has been pretrained on your type of image.

Best regards
Marco
