### ISSUE TITLE
Question about using FrEIA instead of custom NF codes.

### ISSUE THREAD

**Issue by AndSonder** [marco-rudolph/differnet#43]
Hi, very thanks for your contribution！

I find one tools called FrEIA. FrEIA only transform half input in one block. However, you team choose to transform the hole input in your block. What are the advantages of doing this？

Looking forward to your reply！

**Comment by marco-rudolph** [comment]
Hi,

over a long sequence of blocks, it should not make a noticeable difference in practice. 
We took an older version of FrEIA that transformed both halves. The advantage of this technique is that you ensure that the entire input is transformed. Otherwise, if you are unlucky, one variable could not be transformed over all blocks if it falls every time into the non-transformed half.

Best,
Marco
